# Generated by Django 5.1.5 on 2025-02-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='ref_product',
        ),
    ]
